### ISSUE TITLE
Bug in docker container

### ISSUE THREAD

**Issue by rmetcalf9** [rmetcalf9/dockJob#31]
When I have a scheduled task I get this error:

127.0.0.1 - - [09/Apr/2018 16:17:33] "GET /frontend/index.html HTTP/1.1" 200 -
10.0.0.28 - - [09/Apr/2018 16:17:35] "POST /api/jobs/bed06152-a2c9-40bf-a81e-5ac0cd5809a3/execution HTTP/1.1" 200 -
Executing (Execution name = ddsa)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/JobExecutor.py", line 232, in run
    self.loopIteration(curDatetime)
  File "/app/JobExecutor.py", line 217, in loopIteration
    if from_iso8601(self.JobExecutions[curJobExecution].dateCompleted) < timeToPurgeBefore:
  File "/usr/lib/python3.6/site-packages/baseapp_for_restapi_backend_with_swagger/utils.py", line 11, in from_iso8601
    raise Exception('Error - Only conversion of utc times from iso8601 is supported')
Exception: Error - Only conversion of utc times from iso8601 is supported

**Comment by rmetcalf9** [comment]
Some tests:
dateutil.parser.parse('2018-04-09T16:51:48.959823+00:00').tzinfo  #-> 'tzlocal()'
dateutil.parser.parse('2018-04-09T16:51:48.959823 UTC').tzinfo  #-> 'tzlocal()'
dateutil.parser.parse('2018-04-09T16:51:48.959823').tzinfo  #-> ''

always giving me tzlocal.
The following gave me true:

from datetime import datetime
from dateutil.tz import tzutc
from dateutil.tz import tzlocal

tzutc().utcoffset(datetime.now()) == tzlocal().utcoffset(datetime.now())

So change code to:

def from_iso8601(when=None, tz=pytz.timezone("UTC")):
  _when = dateutil.parser.parse(when)
  if not _when.tzinfo:
    _when = tz.localize(_when)
  if (str(_when.tzinfo) != 'tzutc()'):
    if (str(_when.tzinfo) == 'tzlocal()'):
      #if the local time is UTC convert it
      from datetime import datetime
      from dateutil.tz import tzutc
      from dateutil.tz import tzlocal
      if tzutc().utcoffset(datetime.now()) == tzlocal().utcoffset(datetime.now()):
        return _when.replace(tzinfo = tzutc())
      else:
        raise Exception('Error - Only conversion of utc times from iso8601 is supported (Local time returned but not equlivant offset to UTC)')
    else:
      raise Exception('Error - Only conversion of utc times from iso8601 is supported')
  return _when
