### ISSUE TITLE
Command causing error

### ISSUE THREAD

**Issue by rmetcalf9** [rmetcalf9/dockJob#52]
This command gets stuck
'''
wget www.google.com -O-
'''
Future jobs are stuck pending
Implement a timeout for all jobs to terminate them
Work out why this one is getting stuck and fix problem

**Comment by rmetcalf9** [comment]
The following errors in the log describe the issue:
127.0.0.1 - - [30/May/2018 15:14:21] "GET /frontend/index.html HTTP/1.1" 200 -
10.0.0.7 - - [30/May/2018 15:14:24] "POST /api/jobs/70cc120d-fb8a-448a-9bbe-6f63346dafd8/execution HTTP/1.1" 200 -
Executing (Execution name = Aa)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/JobExecutor.py", line 238, in run
    self.loopIteration(curDatetime)
  File "/app/JobExecutor.py", line 197, in loopIteration
    self.appObj.appData['jobsData'].registerRunDetails
  File "/app/JobExecution.py", line 96, in execute
    self.resultSTDOUT = executionResult.stdout.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 8103: invalid start byte

10.0.0.7 - - [30/May/2018 15:14:26] "GET /api/jobs/70cc120d-fb8a-448a-9bbe-6f63346dafd8 HTTP/1.1" 200 -
[2018-05-30 15:14:26,564] ERROR in app: Exception on /api/jobs/70cc120d-fb8a-448a-9bbe-6f63346dafd8/execution [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restplus/marshalling.py", line 101, in wrapper
    resp = f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/baseapp_for_restapi_backend_with_swagger/AppObj.py", line 248, in _
    return funct(*args, **kwargs)
  File "/app/jobsDataAPI.py", line 405, in get
    appObj.jobExecutor.getAllJobExecutions(guid),
  File "/app/JobExecutor.py", line 170, in getAllJobExecutions
    self.aquireJobExecutionLock()
  File "/app/JobExecutor.py", line 116, in aquireJobExecutionLock
    raise Exception("Timedout waiting for lock")
Exception: Timedout waiting for lock

**Comment by rmetcalf9** [comment]
According to https://stackoverflow.com/questions/33283603/python-popen-communicate-str-encodeencoding-utf-8-errors-ignore-cr
I need to add 'utf-8' to the decode statement.

**Comment by rmetcalf9** [comment]
No timeout needs to be implemented. It is already there

**Comment by rmetcalf9** [comment]
The code still needs to be altered so the problem doesn't cause the execution thread to hang.
